# Generated by Django 4.1.2 on 2022-10-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coinfo',
            fields=[
                ('conum', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'container',
                'managed': False,
            },
        ),
    ]
