# Generated by Django 4.1.2 on 2022-10-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinfo',
            options={'managed': True},
        ),
    ]
